### ISSUE TITLE
Add OS-specific instructions

### ISSUE THREAD

**Issue by goldseven** [bitinerant/cleargopher#1]
Currently the instructions assume a Linux or Mac host:

> Telnet to the router: telnet 192.168.8.1

I think it would be helpful to tell the user to "Open a Terminal" and input those commands.

We could also expand the the instructions for Windows 10 users by having them install the Windows Subsystem for Linux. It's as simple as [installing it from the Windows Store now](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6).

Edit: Though if the purpose is just to document the steps to later automate, this might not be necessary.

**Comment by bitinerant** [comment]
Yes - the purpose is to document steps for automation. I'll add a note about this to the instructions.
