### ISSUE TITLE
Evaluate switching from 'yaml' package to 'ruamel.yaml'

### ISSUE THREAD

**Issue by bitinerant** [bitinerant/cleargopher#6]
See [PyYAML dump format](https://stackoverflow.com/a/36760452/10590519).

**Comment by goldseven** [comment]
@bitinerant From everything I know, PyYAML is still the defacto Python YAML library I've seen used everywhere. I'd recommend sticking with it unless we find a really good reason to switch. There was a release less than a year ago and I've seen it used on a lot of work projects successfully.

**Comment by bitinerant** [comment]
Thanks. I'll close this for now. We may come back to this if something changes, i.e. we find PyYAML can't do something we need.
